### ISSUE TITLE
Stop putting tests in examples

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#105]
Tests, while a good idea to have, are not examples. **Examples** are how we want other people (our users!) to write code, **tests** are there to make sure that the code behaves (often in weird edge cases) and are typically not the best code. _Mulching the two together mixes them up in our users' minds,_ and that's a terrible idea.

We should split the tests so that they don't sit beneath the examples folder. (NB: not delete, move.)

**Comment by alan-stokes** [comment]
when i start testing, i go through the easist road to them. if that examples. fine. its when they get to prs that i concur, they should move to tests. but im not going to make my life harder to test to begin with.

**Comment by Christian-B** [comment]
yes I agree. Both good examples and weird egde case should be tested. but not mixed.

I have code in the spynakker8 jenkins2 branch which tests all scripts it finds in a directory.  
Even works when the directory is in another  git repo

**Comment by dkfellows** [comment]
The point is… there's now masses of code in the GFE for complex integration testing of FEC. That's great… except it's not usually what we want to present to users as how they should write their own code.

**Comment by andrewgait** [comment]
There's less if someone reviews https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/100 ...

**Comment by alan-stokes** [comment]
yea, and thats coz andy was nice enough to move them into tests for me...... i think....... i dont really renember who moved what where. but given i was testing data out and data in, and it was GOD DAMN complex. the examples were how i tested them.

**Comment by Christian-B** [comment]
lets keep examples to code we want new master students to look at and COPY

**Comment by alan-stokes** [comment]
example sin master i concur. But i wont do it in my development branches

**Comment by andrewgait** [comment]
Examples and tests are now separated from each other.
