### ISSUE TITLE
Report for missing/lost packets

### ISSUE THREAD

**Issue by gmtuca** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#13]
@alan-stokes 
When sending packets from an arbitrary core to host, a large amount of them drop and the file with such report data is not available.

**Comment by alan-stokes** [comment]
this became apparent that when runnign in a infinite mode, you never get to run provenance, which is valid. If you run end() at any point (which should happen when using the tools at some point) then you would get provanence. therefore closing this issue.
