### ISSUE TITLE
Issue for pull request #129: `buffer_manager` is `None` using a virtual board not catched in the examples

### ISSUE THREAD

**Issue by jofas** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#130]
Issue fixed by: #129. 

I tried running the `hello_world` example with a virtual board and the `buffer_manager` was `None`, resulting in an uncatched `AttributeError`. @alan-stokes already told me that no `buffer_manager` is created by the virtual board and fixed the examples.

Kind regards,
Jonas

**Comment by andrewgait** [comment]
Issue was fixed in recent merge.
