### ISSUE TITLE
examples/template is out of date

### ISSUE THREAD

**Issue by tcstewar** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#62]
It looks like the example code in `examples/template/c_code.c` is out of date.  The code in `examples/hello_world/hello_world.c` seems good, so it should just be a few cut-and-paste type things to get it working.

**Comment by andrewgait** [comment]
Example code updated, further templates added, see https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/63

**Comment by tcstewar** [comment]
Thank you! :)
