### ISSUE TITLE
Verify or fix SDRAM cost model

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#86]
In:
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/blob/master/spinnaker_graph_front_end/examples/Conways/partitioned_example_a_no_vis_no_buffer/conways_basic_cell.py

Please verify the following is correct:
def _calculate_sdram_requirement(self, n_machine_time_steps):
        return (SYSTEM_BYTES_REQUIREMENT +
                self.TRANSMISSION_DATA_SIZE + self.STATE_DATA_SIZE +
                self.NEIGHBOUR_INITIAL_STATES_SIZE +
                n_machine_time_steps + 4)

Which means there is a fixed requirements of:
        return (SYSTEM_BYTES_REQUIREMENT +
                self.TRANSMISSION_DATA_SIZE + self.STATE_DATA_SIZE +
                self.NEIGHBOUR_INITIAL_STATES_SIZE +
                4)

And a per timestep requirement of ONE????

**Comment by alan-stokes** [comment]
i think, that the final + should be a multiply (and bracketed) as its saying that at each timestep there's 1 state to record, which is likely a 4 byte int (for a bool) as it was simpler to store that in record.

**Comment by Christian-B** [comment]
Will be fixed in SDRAM_per_timestep branch/pr so closing,.
