### ISSUE TITLE
examples failing

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#98]
What is the problem you see?
============================
Many of the examples are failing

What do you see that is wrong?
many like
SpiNNFrontEndCommon\spinn_front_end_common\interface\interface_functions\host_execute_data_specification.py:48: ResourceWarning: unclosed file <_io.BufferedReader name= application_generated_data_files\\2019-01-03-12-22-50-189080\\run_1\\192.168.240.253_dataSpec_0_0_2.dat'>
  transceiver, machine, app_id, x, y, p, data_spec_file_path)

and also
spinnman.exceptions.SpinnmanTimeoutException: Operation waiting for cores (0, 0)(1, 0)(1, 1)(0, 1) to reach one of [<CPUState.READY: 5>] timed out after 5 seconds

sys:1: ResourceWarning: unclosed <socket.socket fd=540, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('192.168.240.254', 52708), raddr=('192.168.240.253', 17893)>

What do you think it should do instead?
Work

What version of our software are you using?
-------------------------------------------
master with automatic make run

**Comment by andrewgait** [comment]
This issue was fixed in the referenced merge, so closing.
